const database = [
    // --- 1. LATTAFA ---
    { brand: "Lattafa", name: "Khamrah", price: "165.00", prod_img: "https://lattafa.com/wp-content/uploads/2022/09/Khamrah-1.jpg" },
    { brand: "Lattafa", name: "Asad", price: "115.00", prod_img: "https://lattafa.com/wp-content/uploads/2021/11/Asad-1.jpg" },
    { brand: "Lattafa", name: "Yara", price: "110.00", prod_img: "https://lattafa.com/wp-content/uploads/2020/12/Yara-1.jpg" },
    { brand: "Lattafa", name: "Ameer Al Oudh Intense", price: "95.00", prod_img: "https://lattafa.com/wp-content/uploads/2021/05/Ameer-Al-Oudh-Intense-Oud-1.jpg" },
    { brand: "Lattafa", name: "Bade'e Al Oud (Oud for Glory)", price: "145.00", prod_img: "https://lattafa.com/wp-content/uploads/2020/10/Bade-e-Al-Oud-Oud-for-Glory-1.jpg" },
    { brand: "Lattafa", name: "Pride Nebras", price: "180.00", prod_img: "https://lattafa.com/wp-content/uploads/2022/10/Nebras-1.jpg" },
    { brand: "Lattafa", name: "Fakhar Black", price: "105.00", prod_img: "https://lattafa.com/wp-content/uploads/2021/06/Fakhar-Lattafa-Men-1.jpg" },
    { brand: "Lattafa", name: "Maahir Black Edition", price: "130.00", prod_img: "https://lattafa.com/wp-content/uploads/2020/11/Maahir-Black-Edition-1.jpg" },
    { brand: "Lattafa", name: "Oud Mood", price: "85.00", prod_img: "https://lattafa.com/wp-content/uploads/2020/05/Oud-Mood-1.jpg" },
    { brand: "Lattafa", name: "Sheikh Al Shuyukh Luxe", price: "90.00", prod_img: "https://lattafa.com/wp-content/uploads/2020/05/Sheikh-Al-Shuyukh-Luxe-Edition-1.jpg" },

    // --- 2. DIOR ---
    { brand: "Dior", name: "Sauvage EDT", price: "380.00", prod_img: "https://shop.dior.com.tn/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw6c6c19f5/Y0996452/Y0996452_F099645200_1_Z_E01.jpg" },
    { brand: "Dior", name: "Sauvage Elixir", price: "550.00", prod_img: "https://shop.dior.com.tn/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwc836605e/Y0996460/Y0996460_F099646000_1_Z_E01.jpg" },
    { brand: "Dior", name: "Homme Intense", price: "345.00", prod_img: "https://shop.dior.com.tn/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw18721993/Y0996482/Y0996482_F099648200_1_Z_E01.jpg" },
    { brand: "Dior", name: "J'adore EDP", price: "460.00", prod_img: "https://shop.dior.com.tn/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw7f3b8a3e/Y0066227/Y0066227_F006622700_1_Z_E01.jpg" },
    { brand: "Dior", name: "Miss Dior Blooming Bouquet", price: "390.00", prod_img: "https://shop.dior.com.tn/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw12b4e8c9/Y0996144/Y0996144_F099614400_1_Z_E01.jpg" },
    { brand: "Dior", name: "Gris Dior", price: "850.00", prod_img: "https://shop.dior.com.tn/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwdf9d2c25/Y0996222/Y0996222_F099622200_1_Z_E01.jpg" },
    { brand: "Dior", name: "Fahrenheit EDT", price: "310.00", prod_img: "https://shop.dior.com.tn/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw4c5c2c25/Y0066451/Y0066451_F006645100_1_Z_E01.jpg" },
    { brand: "Dior", name: "Bois d'Argent", price: "850.00", prod_img: "https://shop.dior.com.tn/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw2c2a34b2/Y0996230/Y0996230_F099623000_1_Z_E01.jpg" },
    { brand: "Dior", name: "Ambre Nuit", price: "850.00", prod_img: "https://shop.dior.com.tn/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw1c2a34b2/Y0996231/Y0996231_F099623100_1_Z_E01.jpg" },
    { brand: "Dior", name: "Pure Poison", price: "380.00", prod_img: "https://shop.dior.com.tn/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw4f4a34b2/Y0066220/Y0066220_F006622000_1_Z_E01.jpg" },

    // --- 3. GUERLAIN ---
    { brand: "Guerlain", name: "L'Homme Idéal EDP", price: "330.00", prod_img: "https://www.guerlain.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-Guerlain_Master_Catalog/default/dw4f4a34b2/Lhomme_Ideal_EDP_100ml.jpg" },
    { brand: "Guerlain", name: "Habit Rouge", price: "295.00", prod_img: "https://www.guerlain.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-Guerlain_Master_Catalog/default/dw2c2a34b2/Habit_Rouge_EDT.jpg" },
    { brand: "Guerlain", name: "Shalimar EDP", price: "380.00", prod_img: "https://www.guerlain.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-Guerlain_Master_Catalog/default/dw1c2a34b2/Shalimar_EDP.jpg" },
    { brand: "Guerlain", name: "Mon Guerlain", price: "360.00", prod_img: "https://www.guerlain.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-Guerlain_Master_Catalog/default/dw4f8d5e9b/Mon_Guerlain_EDP.jpg" },
    { brand: "Guerlain", name: "Vetiver", price: "280.00", prod_img: "https://www.guerlain.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-Guerlain_Master_Catalog/default/dw4868589c/Vetiver_EDT.jpg" },
    { brand: "Guerlain", name: "Samsara EDP", price: "350.00", prod_img: "https://www.guerlain.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-Guerlain_Master_Catalog/default/dw1a2b3c/Samsara_EDP.jpg" },
    { brand: "Guerlain", name: "Mitsouko", price: "340.00", prod_img: "https://www.guerlain.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-Guerlain_Master_Catalog/default/dw2b3c4d/Mitsouko_EDP.jpg" },
    { brand: "Guerlain", name: "Aqua Allegoria Mandarine Basilic", price: "310.00", prod_img: "https://www.guerlain.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-Guerlain_Master_Catalog/default/dw3c4d5e/AA_Mandarine.jpg" },
    { brand: "Guerlain", name: "Heritage", price: "300.00", prod_img: "https://www.guerlain.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-Guerlain_Master_Catalog/default/dw4d5e6f/Heritage_EDT.jpg" },
    { brand: "Guerlain", name: "Spiritueuse Double Vanille", price: "980.00", prod_img: "https://www.guerlain.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-Guerlain_Master_Catalog/default/dw5e6f7g/SDV_Parfum.jpg" },
    // --- 4. YVES SAINT LAURENT (YSL) ---
    { brand: "YSL", name: "Libre Le Parfum", price: "415.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw9074a382/Libre_Le_Parfum.jpg" },
    { brand: "YSL", name: "Black Opium Le Parfum", price: "430.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw2670390a/Black_Opium_LP.jpg" },
    { brand: "YSL", name: "Y Eau de Parfum", price: "375.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw6c6c19f5/Y_EDP_100ml.jpg" },
    { brand: "YSL", name: "La Nuit de l'Homme EDT", price: "320.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dwdf9d2c25/LNDH_EDT.jpg" },
    { brand: "YSL", name: "Myslf EDP", price: "385.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw1a2b3c/Myslf_EDP.jpg" },
    { brand: "YSL", name: "Kouros EDT", price: "290.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw2b3c4d/Kouros_EDT.jpg" },
    { brand: "YSL", name: "Tuxedo (Vestiaire)", price: "850.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw3c4d5e/Tuxedo_Parfum.jpg" },
    { brand: "YSL", name: "Opium (Original)", price: "360.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw4d5e6f/Opium_Femme.jpg" },
    { brand: "YSL", name: "Mon Paris EDP", price: "370.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw5e6f7g/Mon_Paris.jpg" },
    { brand: "YSL", name: "L'Homme EDT", price: "310.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw6f7g8h/LHomme_EDT.jpg" },

    // --- 5. GIORGIO ARMANI ---
    { brand: "Armani", name: "Acqua di Giò Profondo", price: "365.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw6c6c19f5/ADG_Profondo.jpg" },
    { brand: "Armani", name: "Sì Intense", price: "420.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dwdf9d2c25/Si_Intense.jpg" },
    { brand: "Armani", name: "Stronger With You Intensely", price: "320.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw1a2b3c/SWY_Intensely.jpg" },
    { brand: "Armani", name: "My Way Le Parfum", price: "440.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw2b3c4d/My_Way_LP.jpg" },
    { brand: "Armani", name: "Armani Code Parfum", price: "395.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw3c4d5e/Code_Parfum.jpg" },
    { brand: "Armani", name: "Acqua di Gioia", price: "310.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw4d5e6f/AD_Gioia.jpg" },
    { brand: "Armani", name: "Rose d'Arabie (Privé)", price: "890.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw5e6f7g/Rose_Arabie.jpg" },
    { brand: "Armani", name: "Oud Royal", price: "890.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw6f7g8h/Oud_Royal.jpg" },
    { brand: "Armani", name: "Thé Yulong", price: "650.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw7g8h9i/The_Yulong.jpg" },
    { brand: "Armani", name: "Rouge Malachite", price: "920.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw8h9i0j/Rouge_Malachite.jpg" },

    // --- 6. TOM FORD ---
    { brand: "Tom Ford", name: "Black Orchid EDP", price: "480.00", prod_img: "https://www.tomford.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-tf-master-catalog/default/dw4f4a34b2/Black_Orchid.jpg" },
    { brand: "Tom Ford", name: "Oud Wood", price: "820.00", prod_img: "https://www.tomford.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-tf-master-catalog/default/dw2c2a34b2/Oud_Wood.jpg" },
    { brand: "Tom Ford", name: "Lost Cherry", price: "950.00", prod_img: "https://www.tomford.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-tf-master-catalog/default/dw1c2a34b2/Lost_Cherry.jpg" },
    { brand: "Tom Ford", name: "Ombré Leather EDP", price: "460.00", prod_img: "https://www.tomford.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-tf-master-catalog/default/dw4f8d5e9b/Ombre_Leather.jpg" },
    { brand: "Tom Ford", name: "Tobacco Vanille", price: "820.00", prod_img: "https://www.tomford.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-tf-master-catalog/default/dw4868589c/Tobacco_Vanille.jpg" },
    { brand: "Tom Ford", name: "Grey Vetiver Parfum", price: "520.00", prod_img: "https://www.tomford.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-tf-master-catalog/default/dw1a2b3c/Grey_Vetiver.jpg" },
    { brand: "Tom Ford", name: "Tuscan Leather", price: "820.00", prod_img: "https://www.tomford.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-tf-master-catalog/default/dw2b3c4d/Tuscan_Leather.jpg" },
    { brand: "Tom Ford", name: "Bitter Peach", price: "950.00", prod_img: "https://www.tomford.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-tf-master-catalog/default/dw3c4d5e/Bitter_Peach.jpg" },
    { brand: "Tom Ford", name: "Soleil Blanc", price: "790.00", prod_img: "https://www.tomford.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-tf-master-catalog/default/dw4d5e6f/Soleil_Blanc.jpg" },
    { brand: "Tom Ford", name: "Beau de Jour", price: "450.00", prod_img: "https://www.tomford.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-tf-master-catalog/default/dw5e6f7g/Beau_de_Jour.jpg" },

    // --- 7. JEAN PAUL GAULTIER ---
    { brand: "JPG", name: "Le Male Elixir", price: "425.00", prod_img: "https://www.jeanpaulgaultier.com/dw/image/v2/BDN_PRD/on/demandware.static/-/Sites-jpg-master-catalog/default/dw6c6c19f5/Le_Male_Elixir.jpg" },
    { brand: "JPG", name: "Scandal Pour Homme", price: "360.00", prod_img: "https://www.jeanpaulgaultier.com/dw/image/v2/BDN_PRD/on/demandware.static/-/Sites-jpg-master-catalog/default/dwdf9d2c25/Scandal_PH.jpg" },
    { brand: "JPG", name: "La Belle Le Parfum", price: "435.00", prod_img: "https://www.jeanpaulgaultier.com/dw/image/v2/BDN_PRD/on/demandware.static/-/Sites-jpg-master-catalog/default/dw1a2b3c/La_Belle_LP.jpg" },
    { brand: "JPG", name: "Ultra Male", price: "370.00", prod_img: "https://www.jeanpaulgaultier.com/dw/image/v2/BDN_PRD/on/demandware.static/-/Sites-jpg-master-catalog/default/dw2b3c4d/Ultra_Male.jpg" },
    { brand: "JPG", name: "Classique EDP", price: "390.00", prod_img: "https://www.jeanpaulgaultier.com/dw/image/v2/BDN_PRD/on/demandware.static/-/Sites-jpg-master-catalog/default/dw3c4d5e/Classique_EDP.jpg" },
    { brand: "JPG", name: "Le Beau Le Parfum", price: "395.00", prod_img: "https://www.jeanpaulgaultier.com/dw/image/v2/BDN_PRD/on/demandware.static/-/Sites-jpg-master-catalog/default/dw4d5e6f/Le_Beau_LP.jpg" },
    { brand: "JPG", name: "Gaultier²", price: "380.00", prod_img: "https://www.jeanpaulgaultier.com/dw/image/v2/BDN_PRD/on/demandware.static/-/Sites-jpg-master-catalog/default/dw5e6f7g/Gaultier2.jpg" },
    { brand: "JPG", name: "Kokorico", price: "280.00", prod_img: "https://www.jeanpaulgaultier.com/dw/image/v2/BDN_PRD/on/demandware.static/-/Sites-jpg-master-catalog/default/dw6f7g8h/Kokorico.jpg" },
    { brand: "JPG", name: "Scandal Le Parfum Femme", price: "410.00", prod_img: "https://www.jeanpaulgaultier.com/dw/image/v2/BDN_PRD/on/demandware.static/-/Sites-jpg-master-catalog/default/dw7g8h9i/Scandal_LP_Femme.jpg" },
    { brand: "JPG", name: "Fragile EDP", price: "450.00", prod_img: "https://www.jeanpaulgaultier.com/dw/image/v2/BDN_PRD/on/demandware.static/-/Sites-jpg-master-catalog/default/dw8h9i0j/Fragile.jpg" },

    // --- 8. CHANEL ---
    { brand: "Chanel", name: "N°5 EDP", price: "480.00", prod_img: "https://www.chanel.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-chanel-master-catalog/default/dw6c6c19f5/N5_EDP.jpg" },
    { brand: "Chanel", name: "Bleu de Chanel Parfum", price: "465.00", prod_img: "https://www.chanel.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-chanel-master-catalog/default/dwdf9d2c25/Bleu_Parfum.jpg" },
    { brand: "Chanel", name: "Coco Mademoiselle", price: "440.00", prod_img: "https://www.chanel.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-chanel-master-catalog/default/dw1a2b3c/Coco_Madem.jpg" },
    { brand: "Chanel", name: "Allure Homme Sport", price: "360.00", prod_img: "https://www.chanel.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-chanel-master-catalog/default/dw2b3c4d/Allure_Sport.jpg" },
    { brand: "Chanel", name: "Égoïste Platinum", price: "340.00", prod_img: "https://www.chanel.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-chanel-master-catalog/default/dw3c4d5e/Platinum.jpg" },
    { brand: "Chanel", name: "Coromandel (Exclusif)", price: "950.00", prod_img: "https://www.chanel.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-chanel-master-catalog/default/dw4d5e6f/Coromandel.jpg" },
    { brand: "Chanel", name: "Sycomore", price: "950.00", prod_img: "https://www.chanel.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-chanel-master-catalog/default/dw5e6f7g/Sycomore.jpg" },
    { brand: "Chanel", name: "Chance Eau Tendre", price: "390.00", prod_img: "https://www.chanel.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-chanel-master-catalog/default/dw6f7g8h/Chance_Tendre.jpg" },
    { brand: "Chanel", name: "Gabrielle Essence", price: "430.00", prod_img: "https://www.chanel.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-chanel-master-catalog/default/dw7g8h9i/Gabrielle.jpg" },
    { brand: "Chanel", name: "Antaeus", price: "350.00", prod_img: "https://www.chanel.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-chanel-master-catalog/default/dw8h9i0j/Antaeus.jpg" },

    // --- 9. FRENCH AVENUE ---
    { brand: "French Avenue", name: "Liquid Brun", price: "185.00", prod_img: "https://fragranceworld.ae/cdn/shop/files/LiquidBrun.jpg" },
    { brand: "French Avenue", name: "Royal Blend", price: "175.00", prod_img: "https://fragranceworld.ae/cdn/shop/files/RoyalBlend.jpg" },
    { brand: "French Avenue", name: "After Eight", price: "160.00", prod_img: "https://fragranceworld.ae/cdn/shop/files/AfterEight.jpg" },
    { brand: "French Avenue", name: "Oud Satin", price: "190.00", prod_img: "https://fragranceworld.ae/cdn/shop/files/OudSatin.jpg" },
    { brand: "French Avenue", name: "Imperial", price: "165.00", prod_img: "https://fragranceworld.ae/cdn/shop/files/Imperial.jpg" },
    { brand: "French Avenue", name: "North Stag III", price: "210.00", prod_img: "https://fragranceworld.ae/cdn/shop/files/NorthStag3.jpg" },
    { brand: "French Avenue", name: "Emir", price: "155.00", prod_img: "https://fragranceworld.ae/cdn/shop/files/Emir.jpg" },
    { brand: "French Avenue", name: "Cedrat", price: "160.00", prod_img: "https://fragranceworld.ae/cdn/shop/files/Cedrat.jpg" },
    { brand: "French Avenue", name: "Royal", price: "170.00", prod_img: "https://fragranceworld.ae/cdn/shop/files/Royal.jpg" },
    { brand: "French Avenue", name: "Gold", price: "165.00", prod_img: "https://fragranceworld.ae/cdn/shop/files/Gold.jpg" },
    // --- 10. ARMAF ---
    { brand: "Armaf", name: "Club de Nuit Intense Man", price: "165.00", prod_img: "https://www.armafperfumes.com/cdn/shop/products/CDNIM_700x.jpg" },
    { brand: "Armaf", name: "Club de Nuit Untold", price: "220.00", prod_img: "https://www.armafperfumes.com/cdn/shop/products/Untold_700x.jpg" },
    { brand: "Armaf", name: "Club de Nuit Iconic", price: "195.00", prod_img: "https://www.armafperfumes.com/cdn/shop/products/Iconic_700x.jpg" },
    { brand: "Armaf", name: "Club de Nuit Milestone", price: "175.00", prod_img: "https://www.armafperfumes.com/cdn/shop/products/Milestone_700x.jpg" },
    { brand: "Armaf", name: "Club de Nuit Sillage", price: "170.00", prod_img: "https://www.armafperfumes.com/cdn/shop/products/Sillage_700x.jpg" },
    { brand: "Armaf", name: "Club de Nuit Urban Elixir", price: "180.00", prod_img: "https://www.armafperfumes.com/cdn/shop/products/UrbanElixir_700x.jpg" },
    { brand: "Armaf", name: "Hunter Intense", price: "110.00", prod_img: "https://www.armafperfumes.com/cdn/shop/products/HunterIntense_700x.jpg" },
    { brand: "Armaf", name: "Craze", price: "115.00", prod_img: "https://www.armafperfumes.com/cdn/shop/products/Craze_700x.jpg" },
    { brand: "Armaf", name: "The Pride of Armaf", price: "125.00", prod_img: "https://www.armafperfumes.com/cdn/shop/products/Pride_700x.jpg" },
    { brand: "Armaf", name: "Buena Vista", price: "105.00", prod_img: "https://www.armafperfumes.com/cdn/shop/products/BuenaVista_700x.jpg" },

    // --- 11. AMOUAGE ---
    { brand: "Amouage", name: "Reflection Man", price: "1150.00", prod_img: "https://www.amouage.com/media/catalog/product/r/e/reflection_man_1.jpg" },
    { brand: "Amouage", name: "Interlude Man", price: "1080.00", prod_img: "https://www.amouage.com/media/catalog/product/i/n/interlude_man_1.jpg" },
    { brand: "Amouage", name: "Jubilation XXV", price: "1120.00", prod_img: "https://www.amouage.com/media/catalog/product/j/u/jubilation_xxv_man.jpg" },
    { brand: "Amouage", name: "Guidance", price: "1250.00", prod_img: "https://www.amouage.com/media/catalog/product/g/u/guidance_1.jpg" },
    { brand: "Amouage", name: "Epic Man", price: "1050.00", prod_img: "https://www.amouage.com/media/catalog/product/e/p/epic_man.jpg" },
    { brand: "Amouage", name: "Lyric Man", price: "980.00", prod_img: "https://www.amouage.com/media/catalog/product/l/y/lyric_man.jpg" },
    { brand: "Amouage", name: "Beach Hut Man", price: "1020.00", prod_img: "https://www.amouage.com/media/catalog/product/b/e/beach_hut.jpg" },
    { brand: "Amouage", name: "Overture Man", price: "1350.00", prod_img: "https://www.amouage.com/media/catalog/product/o/v/overture.jpg" },
    { brand: "Amouage", name: "Royal Tobacco", price: "1450.00", prod_img: "https://www.amouage.com/media/catalog/product/r/o/royal_tobacco.jpg" },
    { brand: "Amouage", name: "Sunshine Man", price: "950.00", prod_img: "https://www.amouage.com/media/catalog/product/s/u/sunshine.jpg" },

    // --- 12. XERJOFF ---
    { brand: "Xerjoff", name: "Naxos", price: "890.00", prod_img: "https://www.xerjoff.com/images/products/naxos.jpg" },
    { brand: "Xerjoff", name: "Erba Pura", price: "850.00", prod_img: "https://www.xerjoff.com/images/products/erbapura.jpg" },
    { brand: "Xerjoff", name: "Alexandria II", price: "1450.00", prod_img: "https://www.xerjoff.com/images/products/alexandria2.jpg" },
    { brand: "Xerjoff", name: "Lira", price: "780.00", prod_img: "https://www.xerjoff.com/images/products/lira.jpg" },
    { brand: "Xerjoff", name: "Mefisto", price: "760.00", prod_img: "https://www.xerjoff.com/images/products/mefisto.jpg" },
    { brand: "Xerjoff", name: "Tony Iommi Monkey Special", price: "1200.00", prod_img: "https://www.xerjoff.com/images/products/monkey.jpg" },
    { brand: "Xerjoff", name: "Accento", price: "790.00", prod_img: "https://www.xerjoff.com/images/products/accento.jpg" },
    { brand: "Xerjoff", name: "Uden", price: "880.00", prod_img: "https://www.xerjoff.com/images/products/uden.jpg" },
    { brand: "Xerjoff", name: "More Than Words", price: "820.00", prod_img: "https://www.xerjoff.com/images/products/mtw.jpg" },
    { brand: "Xerjoff", name: "Kobe", price: "910.00", prod_img: "https://www.xerjoff.com/images/products/kobe.jpg" },

    // --- 13. ZARA ---
    { brand: "Zara", name: "Vibrant Leather", price: "115.00", prod_img: "https://static.zara.net/photos/vibrant_leather.jpg" },
    { brand: "Zara", name: "Red Temptation", price: "95.00", prod_img: "https://static.zara.net/photos/red_temptation.jpg" },
    { brand: "Zara", name: "Tobacco Collection RWA", price: "85.00", prod_img: "https://static.zara.net/photos/tobacco_rwa.jpg" },
    { brand: "Zara", name: "Ebony Wood", price: "105.00", prod_img: "https://static.zara.net/photos/ebony_wood.jpg" },
    { brand: "Zara", name: "Sunrise on the Red Sand Dunes", price: "110.00", prod_img: "https://static.zara.net/photos/sunrise.jpg" },
    { brand: "Zara", name: "Sand Desert at Sunset", price: "110.00", prod_img: "https://static.zara.net/photos/sand_desert.jpg" },
    { brand: "Zara", name: "Bogoss Vibrant Leather", price: "95.00", prod_img: "https://static.zara.net/photos/bogoss.jpg" },
    { brand: "Zara", name: "Navy Black", price: "75.00", prod_img: "https://static.zara.net/photos/navy_black.jpg" },
    { brand: "Zara", name: "Seoul", price: "75.00", prod_img: "https://static.zara.net/photos/seoul.jpg" },
    { brand: "Zara", name: "Lisboa", price: "75.00", prod_img: "https://static.zara.net/photos/lisboa.jpg" },

    // --- 14. PARFUMS DE MARLY ---
    { brand: "Parfums de Marly", name: "Layton", price: "950.00", prod_img: "https://parfums-de-marly.com/cdn/shop/products/Layton.jpg" },
    { brand: "Parfums de Marly", name: "Herod", price: "920.00", prod_img: "https://parfums-de-marly.com/cdn/shop/products/Herod.jpg" },
    { brand: "Parfums de Marly", name: "Haltane", price: "1050.00", prod_img: "https://parfums-de-marly.com/cdn/shop/products/Haltane.jpg" },
    { brand: "Parfums de Marly", name: "Percival", price: "880.00", prod_img: "https://parfums-de-marly.com/cdn/shop/products/Percival.jpg" },
    { brand: "Parfums de Marly", name: "Pegasus Exclusif", price: "980.00", prod_img: "https://parfums-de-marly.com/cdn/shop/products/Pegasus.jpg" },
    { brand: "Parfums de Marly", name: "Carlisle", price: "1100.00", prod_img: "https://parfums-de-marly.com/cdn/shop/products/Carlisle.jpg" },
    { brand: "Parfums de Marly", name: "Delina Exclusif", price: "980.00", prod_img: "https://parfums-de-marly.com/cdn/shop/products/Delina.jpg" },
    { brand: "Parfums de Marly", name: "Oajan", price: "950.00", prod_img: "https://parfums-de-marly.com/cdn/shop/products/Oajan.jpg" },
    { brand: "Parfums de Marly", name: "Greenley", price: "890.00", prod_img: "https://parfums-de-marly.com/cdn/shop/products/Greenley.jpg" },
    { brand: "Parfums de Marly", name: "Habdan", price: "920.00", prod_img: "https://parfums-de-marly.com/cdn/shop/products/Habdan.jpg" },

    // --- 15. VERSACE ---
    { brand: "Versace", name: "Eros EDP", price: "345.00", prod_img: "https://www.versace.com/dw/image/v2/ABAQ_PRD/on/demandware.static/-/Sites-ver-master-catalog/default/dw4f4a34b2/Eros_EDP.jpg" },
    { brand: "Versace", name: "Eros Flame", price: "345.00", prod_img: "https://www.versace.com/dw/image/v2/ABAQ_PRD/on/demandware.static/-/Sites-ver-master-catalog/default/dw2c2a34b2/Eros_Flame.jpg" },
    { brand: "Versace", name: "Dylan Blue", price: "295.00", prod_img: "https://www.versace.com/dw/image/v2/ABAQ_PRD/on/demandware.static/-/Sites-ver-master-catalog/default/dw3c4d5e/Dylan_Blue.jpg" },
    { brand: "Versace", name: "Pour Homme", price: "280.00", prod_img: "https://www.versace.com/dw/image/v2/ABAQ_PRD/on/demandware.static/-/Sites-ver-master-catalog/default/dw4d5e6f/Versace_PH.jpg" },
    { brand: "Versace", name: "Eau Fraiche", price: "270.00", prod_img: "https://www.versace.com/dw/image/v2/ABAQ_PRD/on/demandware.static/-/Sites-ver-master-catalog/default/dw5e6f7g/Eau_Fraiche.jpg" },
    { brand: "Versace", name: "Crystal Noir", price: "380.00", prod_img: "https://www.versace.com/dw/image/v2/ABAQ_PRD/on/demandware.static/-/Sites-ver-master-catalog/default/dw6f7g8h/Crystal_Noir.jpg" },
    { brand: "Versace", name: "Bright Crystal", price: "320.00", prod_img: "https://www.versace.com/dw/image/v2/ABAQ_PRD/on/demandware.static/-/Sites-ver-master-catalog/default/dw7g8h9i/Bright_Crystal.jpg" },
    { brand: "Versace", name: "The Dreamer", price: "220.00", prod_img: "https://www.versace.com/dw/image/v2/ABAQ_PRD/on/demandware.static/-/Sites-ver-master-catalog/default/dw8h9i0j/Dreamer.jpg" },
    { brand: "Versace", name: "Versace Oud Noir", price: "395.00", prod_img: "https://www.versace.com/dw/image/v2/ABAQ_PRD/on/demandware.static/-/Sites-ver-master-catalog/default/dw9i0j1k/Oud_Noir.jpg" },
    { brand: "Versace", name: "Blue Jeans", price: "110.00", prod_img: "https://www.versace.com/dw/image/v2/ABAQ_PRD/on/demandware.static/-/Sites-ver-master-catalog/default/dw0j1k2l/Blue_Jeans.jpg" },

    // --- 16. DOLCE & GABBANA ---
    { brand: "D&G", name: "The One EDP", price: "365.00", prod_img: "https://www.dolcegabbana.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-dg-master-catalog/default/dw6c6c19f5/The_One_EDP.jpg" },
    { brand: "D&G", name: "The One Royal Night", price: "420.00", prod_img: "https://www.dolcegabbana.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-dg-master-catalog/default/dwdf9d2c25/Royal_Night.jpg" },
    { brand: "D&G", name: "Light Blue Intense", price: "320.00", prod_img: "https://www.dolcegabbana.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-dg-master-catalog/default/dw1a2b3c/LB_Intense.jpg" },
    { brand: "D&G", name: "K by Dolce & Gabbana EDP", price: "340.00", prod_img: "https://www.dolcegabbana.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-dg-master-catalog/default/dw2b3c4d/K_EDP.jpg" },
    { brand: "D&G", name: "The Only One", price: "380.00", prod_img: "https://www.dolcegabbana.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-dg-master-catalog/default/dw3c4d5e/Only_One.jpg" },
    { brand: "D&G", name: "Pour Homme", price: "290.00", prod_img: "https://www.dolcegabbana.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-dg-master-catalog/default/dw4d5e6f/DG_PH.jpg" },
    { brand: "D&G", name: "Intenso", price: "285.00", prod_img: "https://www.dolcegabbana.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-dg-master-catalog/default/dw5e6f7g/Intenso.jpg" },
    { brand: "D&G", name: "L'Imperatrice", price: "240.00", prod_img: "https://www.dolcegabbana.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-dg-master-catalog/default/dw6f7g8h/Imperatrice.jpg" },
    { brand: "D&G", name: "Devotion", price: "410.00", prod_img: "https://www.dolcegabbana.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-dg-master-catalog/default/dw7g8h9i/Devotion.jpg" },
    { brand: "D&G", name: "Light Blue Pour Homme", price: "275.00", prod_img: "https://www.dolcegabbana.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-dg-master-catalog/default/dw8h9i0j/LB_Homme.jpg" },
    // --- 17. BY KILIAN ---
    { brand: "Kilian", name: "Angels' Share", price: "850.00", prod_img: "https://www.bykilian.fr/media/export/cms/products/600x600/kil_sku_N32601_600x600_0.jpg" },
    { brand: "Kilian", name: "Black Phantom", price: "820.00", prod_img: "https://www.bykilian.fr/media/export/cms/products/600x600/kil_sku_N23401_600x600_0.jpg" },
    { brand: "Kilian", name: "Love, Don't Be Shy", price: "910.00", prod_img: "https://www.bykilian.fr/media/export/cms/products/600x600/kil_sku_N12301_600x600_0.jpg" },
    { brand: "Kilian", name: "Straight to Heaven", price: "850.00", prod_img: "https://www.bykilian.fr/media/export/cms/products/600x600/kil_sku_N11101_600x600_0.jpg" },
    { brand: "Kilian", name: "Moonlight in Heaven", price: "850.00", prod_img: "https://www.bykilian.fr/media/export/cms/products/600x600/kil_sku_N22201_600x600_0.jpg" },
    { brand: "Kilian", name: "Good Girl Gone Bad", price: "890.00", prod_img: "https://www.bykilian.fr/media/export/cms/products/600x600/kil_sku_N11201_600x600_0.jpg" },
    { brand: "Kilian", name: "Apple Brandy on the Rocks", price: "780.00", prod_img: "https://www.bykilian.fr/media/export/cms/products/600x600/kil_sku_N44401_600x600_0.jpg" },
    { brand: "Kilian", name: "Roses on Ice", price: "750.00", prod_img: "https://www.bykilian.fr/media/export/cms/products/600x600/kil_sku_N44501_600x600_0.jpg" },
    { brand: "Kilian", name: "Vodka on the Rocks", price: "820.00", prod_img: "https://www.bykilian.fr/media/export/cms/products/600x600/kil_sku_N33301_600x600_0.jpg" },
    { brand: "Kilian", name: "Smoking Hot", price: "880.00", prod_img: "https://www.bykilian.fr/media/export/cms/products/600x600/kil_sku_N55501_600x600_0.jpg" },

    // --- 18. MAISON FRANCIS KURKDJIAN (MFK) ---
    { brand: "MFK", name: "Baccarat Rouge 540 EDP", price: "1150.00", prod_img: "https://www.franciskurkdjian.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-mfk-master-catalog/default/dw6c6c19f5/BR540_EDP.jpg" },
    { brand: "MFK", name: "Baccarat Rouge 540 Extrait", price: "1550.00", prod_img: "https://www.franciskurkdjian.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-mfk-master-catalog/default/dwdf9d2c25/BR540_Extrait.jpg" },
    { brand: "MFK", name: "Grand Soir", price: "720.00", prod_img: "https://www.franciskurkdjian.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-mfk-master-catalog/default/dw1a2b3c/Grand_Soir.jpg" },
    { brand: "MFK", name: "Gentle Fluidity Gold", price: "750.00", prod_img: "https://www.franciskurkdjian.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-mfk-master-catalog/default/dw2b3c4d/GF_Gold.jpg" },
    { brand: "MFK", name: "Gentle Fluidity Silver", price: "750.00", prod_img: "https://www.franciskurkdjian.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-mfk-master-catalog/default/dw3c4d5e/GF_Silver.jpg" },
    { brand: "MFK", name: "Oud Satin Mood EDP", price: "890.00", prod_img: "https://www.franciskurkdjian.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-mfk-master-catalog/default/dw4d5e6f/Oud_Satin.jpg" },
    { brand: "MFK", name: "724 EDP", price: "780.00", prod_img: "https://www.franciskurkdjian.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-mfk-master-catalog/default/dw5e6f7g/724_EDP.jpg" },
    { brand: "MFK", name: "Amyris Homme Extrait", price: "720.00", prod_img: "https://www.franciskurkdjian.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-mfk-master-catalog/default/dw6f7g8h/Amyris_Homme.jpg" },
    { brand: "MFK", name: "Aqua Celestia Forte", price: "680.00", prod_img: "https://www.franciskurkdjian.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-mfk-master-catalog/default/dw7g8h9i/Aqua_Celestia.jpg" },
    { brand: "MFK", name: "L'Homme À la Rose", price: "690.00", prod_img: "https://www.franciskurkdjian.com/dw/image/v2/BDNH_PRD/on/demandware.static/-/Sites-mfk-master-catalog/default/dw8h9i0j/Homme_Rose.jpg" },

    // --- 20. PACO RABANNE ---
    { brand: "Rabanne", name: "1 Million Elixir", price: "410.00", prod_img: "https://www.rabanne.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-rabanne-master-catalog/default/dw7f3b8a3e/1M_Elixir.jpg" },
    { brand: "Rabanne", name: "1 Million Lucky", price: "340.00", prod_img: "https://www.rabanne.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-rabanne-master-catalog/default/dw12b4e8c9/1M_Lucky.jpg" },
    { brand: "Rabanne", name: "Invictus Victory Elixir", price: "425.00", prod_img: "https://www.rabanne.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-rabanne-master-catalog/default/dw4c5c2c25/Invictus_Victory_Elixir.jpg" },
    { brand: "Rabanne", name: "Phantom Intense", price: "395.00", prod_img: "https://www.rabanne.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-rabanne-master-catalog/default/dw2c2a34b2/Phantom_Intense.jpg" },
    { brand: "Rabanne", name: "Pure XS Night", price: "330.00", prod_img: "https://www.rabanne.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-rabanne-master-catalog/default/dw1c2a34b2/Pure_XS_Night.jpg" },
    { brand: "Rabanne", name: "Olympéa Flora", price: "390.00", prod_img: "https://www.rabanne.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-rabanne-master-catalog/default/dw4f8d5e9b/Olympea_Flora.jpg" },
    { brand: "Rabanne", name: "Lady Million Royal", price: "385.00", prod_img: "https://www.rabanne.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-rabanne-master-catalog/default/dw4868589c/Lady_M_Royal.jpg" },
    { brand: "Rabanne", name: "Invictus Platinum", price: "360.00", prod_img: "https://www.rabanne.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-rabanne-master-catalog/default/dw1a2b3c/Invictus_Platinum.jpg" },
    { brand: "Rabanne", name: "1 Million Royal", price: "410.00", prod_img: "https://www.rabanne.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-rabanne-master-catalog/default/dw2b3c4d/1M_Royal.jpg" },
    { brand: "Rabanne", name: "Fame Parfum", price: "420.00", prod_img: "https://www.rabanne.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-rabanne-master-catalog/default/dw3c4d5e/Fame_Parfum.jpg" },

    // --- 21. AFNAN ---
    { brand: "Afnan", name: "9PM Black", price: "125.00", prod_img: "https://afnan.com/cdn/shop/products/9PM_Black.jpg" },
    { brand: "Afnan", name: "9AM Dive", price: "115.00", prod_img: "https://afnan.com/cdn/shop/products/9AM_Dive.jpg" },
    { brand: "Afnan", name: "Turathi Blue", price: "145.00", prod_img: "https://afnan.com/cdn/shop/products/Turathi_Blue.jpg" },
    { brand: "Afnan", name: "Supremacy Not Only Intense", price: "185.00", prod_img: "https://afnan.com/cdn/shop/products/SNOI.jpg" },
    { brand: "Afnan", name: "Supremacy Silver", price: "135.00", prod_img: "https://afnan.com/cdn/shop/products/Supremacy_Silver.jpg" },
    { brand: "Afnan", name: "Rare Carbon", price: "110.00", prod_img: "https://afnan.com/cdn/shop/products/Rare_Carbon.jpg" },
    { brand: "Afnan", name: "Modest Une", price: "105.00", prod_img: "https://afnan.com/cdn/shop/products/Modest_Une.jpg" },
    { brand: "Afnan", name: "Snooze", price: "140.00", prod_img: "https://afnan.com/cdn/shop/products/Snooze.jpg" },
    { brand: "Afnan", name: "Zimaya Sharaf Blend", price: "130.00", prod_img: "https://afnan.com/cdn/shop/products/Sharaf_Blend.jpg" },
    { brand: "Afnan", name: "Turathi Brown", price: "155.00", prod_img: "https://afnan.com/cdn/shop/products/Turathi_Brown.jpg" },

    // --- 22. MAISON ALHAMBRA ---
    { brand: "Maison Alhambra", name: "Porto Neroli", price: "95.00", prod_img: "https://lattafa.com/wp-content/uploads/2022/10/Porto-Neroli.jpg" },
    { brand: "Maison Alhambra", name: "Woody Oud", price: "90.00", prod_img: "https://lattafa.com/wp-content/uploads/2022/10/Woody-Oud.jpg" },
    { brand: "Maison Alhambra", name: "Lovely Cherie", price: "100.00", prod_img: "https://lattafa.com/wp-content/uploads/2022/10/Lovely-Cherie.jpg" },
    { brand: "Maison Alhambra", name: "Toscano Leather", price: "110.00", prod_img: "https://lattafa.com/wp-content/uploads/2022/10/Toscano-Leather.jpg" },
    { brand: "Maison Alhambra", name: "Bright Peach", price: "95.00", prod_img: "https://lattafa.com/wp-content/uploads/2022/10/Bright-Peach.jpg" },
    { brand: "Maison Alhambra", name: "Rose Petals", price: "95.00", prod_img: "https://lattafa.com/wp-content/uploads/2022/10/Rose-Petals.jpg" },
    { brand: "Maison Alhambra", name: "Fabulo Intense", price: "105.00", prod_img: "https://lattafa.com/wp-content/uploads/2022/10/Fabulo-Intense.jpg" },
    { brand: "Maison Alhambra", name: "Tobacco Touch", price: "100.00", prod_img: "https://lattafa.com/wp-content/uploads/2022/10/Tobacco-Touch.jpg" },
    { brand: "Maison Alhambra", name: "Kismet Angel", price: "115.00", prod_img: "https://lattafa.com/wp-content/uploads/2022/10/Kismet-Angel.jpg" },
    { brand: "Maison Alhambra", name: "The Tux", price: "140.00", prod_img: "https://lattafa.com/wp-content/uploads/2022/10/The-Tux.jpg" },
    // --- 23. LOUIS VUITTON ---
    { brand: "Louis Vuitton", name: "Ombre Nomade", price: "1450.00", prod_img: "https://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_AS/louis-vuitton-ombre-nomade--LP0095_PM2_Front%20view.jpg" },
    { brand: "Louis Vuitton", name: "Imagination", price: "1100.00", prod_img: "https://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_AS/louis-vuitton-imagination--LP0219_PM2_Front%20view.jpg" },
    { brand: "Louis Vuitton", name: "L'Immensité", price: "1100.00", prod_img: "https://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_AS/louis-vuitton-l-immensite--LP0052_PM2_Front%20view.jpg" },
    { brand: "Louis Vuitton", name: "Afternoon Swim", price: "1100.00", prod_img: "https://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_AS/louis-vuitton-afternoon-swim--LP0128_PM2_Front%20view.jpg" },
    { brand: "Louis Vuitton", name: "Météore", price: "1100.00", prod_img: "https://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_AS/louis-vuitton-meteore--LP0160_PM2_Front%20view.jpg" },
    { brand: "Louis Vuitton", name: "Pacific Chill", price: "1100.00", prod_img: "https://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_AS/louis-vuitton-pacific-chill--LP0326_PM2_Front%20view.jpg" },
    { brand: "Louis Vuitton", name: "Attrape-Rêves", price: "1100.00", prod_img: "https://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_AS/louis-vuitton-attrape-reves--LP0091_PM2_Front%20view.jpg" },
    { brand: "Louis Vuitton", name: "Nouveau Monde", price: "1100.00", prod_img: "https://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_AS/louis-vuitton-nouveau-monde--LP0053_PM2_Front%20view.jpg" },
    { brand: "Louis Vuitton", name: "Rose des Vents", price: "1100.00", prod_img: "https://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_AS/louis-vuitton-rose-des-vents--LP0005_PM2_Front%20view.jpg" },
    { brand: "Louis Vuitton", name: "Symphony (Extrait)", price: "1850.00", prod_img: "https://fr.louisvuitton.com/images/is/image/lv/1/PP_VP_AS/louis-vuitton-symphony--LP0249_PM2_Front%20view.jpg" },

    // --- 24. MANCERA ---
    { brand: "Mancera", name: "Cedrat Boise", price: "380.00", prod_img: "https://manceraparfums.com/img/p/cedrat_boise_120.jpg" },
    { brand: "Mancera", name: "Red Tobacco", price: "410.00", prod_img: "https://manceraparfums.com/img/p/red_tobacco_120.jpg" },
    { brand: "Mancera", name: "Instant Crush", price: "410.00", prod_img: "https://manceraparfums.com/img/p/instant_crush_120.jpg" },
    { brand: "Mancera", name: "Roses Vanille", price: "390.00", prod_img: "https://manceraparfums.com/img/p/roses_vanille_120.jpg" },
    { brand: "Mancera", name: "Aoud Lemon Mint", price: "380.00", prod_img: "https://manceraparfums.com/img/p/aoud_lemon_mint_120.jpg" },
    { brand: "Mancera", name: "Hindu Kush", price: "380.00", prod_img: "https://manceraparfums.com/img/p/hindu_kush_120.jpg" },
    { brand: "Mancera", name: "Black Gold", price: "380.00", prod_img: "https://manceraparfums.com/img/p/black_gold_120.jpg" },
    { brand: "Mancera", name: "Saharian Wind", price: "380.00", prod_img: "https://manceraparfums.com/img/p/saharian_wind_120.jpg" },
    { brand: "Mancera", name: "Coco Vanille", price: "380.00", prod_img: "https://manceraparfums.com/img/p/coco_vanille_120.jpg" },
    { brand: "Mancera", name: "Holiday", price: "380.00", prod_img: "https://manceraparfums.com/img/p/holiday_120.jpg" },

    // --- 25. VALENTINO ---
    { brand: "Valentino", name: "Born In Roma Coral Fantasy", price: "395.00", prod_img: "https://www.valentino.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-valentino-master-catalog/default/dw1c2a34b2/coral_fantasy_homme.jpg" },
    { brand: "Valentino", name: "Born In Roma Intense Homme", price: "415.00", prod_img: "https://www.valentino.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-valentino-master-catalog/default/dwc836605e/bir_intense_homme.jpg" },
    { brand: "Valentino", name: "Uomo Intense", price: "380.00", prod_img: "https://www.valentino.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-valentino-master-catalog/default/dwf4b1a45d/valentino_uomo_intense.jpg" },
    { brand: "Valentino", name: "Born In Roma Yellow Dream", price: "360.00", prod_img: "https://www.valentino.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-valentino-master-catalog/default/dw4f8d5e9b/yellow_dream_homme.jpg" },
    { brand: "Valentino", name: "Donna Born In Roma", price: "420.00", prod_img: "https://www.valentino.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-valentino-master-catalog/default/dw4868589c/donna_bir.jpg" },
    { brand: "Valentino", name: "Uomo Born In Roma EDT", price: "360.00", prod_img: "https://www.valentino.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-valentino-master-catalog/default/dw1a2b3c/uomo_bir_edt.jpg" },
    { brand: "Valentino", name: "Voce Viva", price: "410.00", prod_img: "https://www.valentino.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-valentino-master-catalog/default/dw2b3c4d/voce_viva.jpg" },
    { brand: "Valentino", name: "Uomo Acqua", price: "320.00", prod_img: "https://www.valentino.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-valentino-master-catalog/default/dw3c4d5e/uomo_acqua.jpg" },
    { brand: "Valentino", name: "Donna Born In Roma Green Stravaganza", price: "440.00", prod_img: "https://www.valentino.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-valentino-master-catalog/default/dw4d5e6f/green_stravaganza.jpg" },
    { brand: "Valentino", name: "Uomo (Original)", price: "340.00", prod_img: "https://www.valentino.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-valentino-master-catalog/default/dw5e6f7g/valentino_uomo.jpg" },

    // --- 26. CAROLINA HERRERA ---
    { brand: "Carolina Herrera", name: "Bad Boy Cobalt Elixir", price: "440.00", prod_img: "https://www.carolinaherrera.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-herrera-master-catalog/default/dw6c6c19f5/Bad_Boy_Cobalt_Elixir.jpg" },
    { brand: "Carolina Herrera", name: "Good Girl Blush", price: "425.00", prod_img: "https://www.carolinaherrera.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-herrera-master-catalog/default/dwdf9d2c25/Good_Girl_Blush.jpg" },
    { brand: "Carolina Herrera", name: "Bad Boy Le Parfum", price: "390.00", prod_img: "https://www.carolinaherrera.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-herrera-master-catalog/default/dw1a2b3c/Bad_Boy_LP.jpg" },
    { brand: "Carolina Herrera", name: "Good Girl Supreme", price: "460.00", prod_img: "https://www.carolinaherrera.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-herrera-master-catalog/default/dw2b3c4d/Good_Girl_Supreme.jpg" },
    { brand: "Carolina Herrera", name: "212 VIP Black", price: "340.00", prod_img: "https://www.carolinaherrera.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-herrera-master-catalog/default/dw3c4d5e/212_VIP_Black.jpg" },
    { brand: "Carolina Herrera", name: "CH Men Prive", price: "380.00", prod_img: "https://www.carolinaherrera.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-herrera-master-catalog/default/dw4d5e6f/CH_Men_Prive.jpg" },
    { brand: "Carolina Herrera", name: "Good Girl (Original)", price: "410.00", prod_img: "https://www.carolinaherrera.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-herrera-master-catalog/default/dw5e6f7g/Good_Girl_EDP.jpg" },
    { brand: "Carolina Herrera", name: "Bad Boy EDT", price: "350.00", prod_img: "https://www.carolinaherrera.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-herrera-master-catalog/default/dw6f7g8h/Bad_Boy_EDT.jpg" },
    { brand: "Carolina Herrera", name: "212 Sexy Men", price: "280.00", prod_img: "https://www.carolinaherrera.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-herrera-master-catalog/default/dw7g8h9i/212_Sexy_Men.jpg" },
    { brand: "Carolina Herrera", name: "Very Good Girl", price: "430.00", prod_img: "https://www.carolinaherrera.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-herrera-master-catalog/default/dw8h9i0j/Very_Good_Girl.jpg" },

    // --- 27. DIPTYQUE ---
    { brand: "Diptyque", name: "Philosykos EDP", price: "580.00", prod_img: "https://www.diptyqueparis.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-diptyque-master-catalog/default/dw1a2b3c/Philosykos.jpg" },
    { brand: "Diptyque", name: "Do Son EDP", price: "580.00", prod_img: "https://www.diptyqueparis.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-diptyque-master-catalog/default/dw2b3c4d/Do_Son.jpg" },
    { brand: "Diptyque", name: "Tam Dao EDP", price: "580.00", prod_img: "https://www.diptyqueparis.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-diptyque-master-catalog/default/dw3c4d5e/Tam_Dao.jpg" },
    { brand: "Diptyque", name: "Fleur de Peau", price: "580.00", prod_img: "https://www.diptyqueparis.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-diptyque-master-catalog/default/dw4d5e6f/Fleur_de_Peau.jpg" },
    { brand: "Diptyque", name: "Eau Capitale", price: "580.00", prod_img: "https://www.diptyqueparis.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-diptyque-master-catalog/default/dw5e6f7g/Eau_Capitale.jpg" },
    { brand: "Diptyque", name: "L'Ombre dans l'Eau", price: "560.00", prod_img: "https://www.diptyqueparis.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-diptyque-master-catalog/default/dw6f7g8h/LOmbre.jpg" },
    { brand: "Diptyque", name: "Orphéon", price: "610.00", prod_img: "https://www.diptyqueparis.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-diptyque-master-catalog/default/dw7g8h9i/Orpheon.jpg" },
    { brand: "Diptyque", name: "Volutes EDP", price: "580.00", prod_img: "https://www.diptyqueparis.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-diptyque-master-catalog/default/dw8h9i0j/Volutes.jpg" },
    { brand: "Diptyque", name: "34 Boulevard Saint Germain", price: "650.00", prod_img: "https://www.diptyqueparis.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-diptyque-master-catalog/default/dw9i0j1k/34_Boulevard.jpg" },
    { brand: "Diptyque", name: "Eau Duelle EDP", price: "580.00", prod_img: "https://www.diptyqueparis.com/dw/image/v2/BCRM_PRD/on/demandware.static/-/Sites-diptyque-master-catalog/default/dw0j1k2l/Eau_Duelle.jpg" },

    // --- 28. CREED ---
    { brand: "Creed", name: "Aventus", price: "1350.00", prod_img: "https://www.creedfragrance.com/cdn/shop/files/Aventus_100ml.jpg" },
    { brand: "Creed", name: "Aventus For Her", price: "1200.00", prod_img: "https://www.creedfragrance.com/cdn/shop/files/Aventus_For_Her.jpg" },
    { brand: "Creed", name: "Green Irish Tweed", price: "980.00", prod_img: "https://www.creedfragrance.com/cdn/shop/files/GIT_100ml.jpg" },
    { brand: "Creed", name: "Silver Mountain Water", price: "980.00", prod_img: "https://www.creedfragrance.com/cdn/shop/files/SMW_100ml.jpg" },
    { brand: "Creed", name: "Millésime Impérial", price: "950.00", prod_img: "https://www.creedfragrance.com/cdn/shop/files/MI_100ml.jpg" },
    { brand: "Creed", name: "Original Santal", price: "920.00", prod_img: "https://www.creedfragrance.com/cdn/shop/files/Original_Santal.jpg" },
    { brand: "Creed", name: "Royal Oud", price: "1150.00", prod_img: "https://www.creedfragrance.com/cdn/shop/files/Royal_Oud.jpg" },
    { brand: "Creed", name: "Virgin Island Water", price: "950.00", prod_img: "https://www.creedfragrance.com/cdn/shop/files/VIW.jpg" },
    { brand: "Creed", name: "Himalaya", price: "920.00", prod_img: "https://www.creedfragrance.com/cdn/shop/files/Himalaya.jpg" },
    { brand: "Creed", name: "Viking", price: "980.00", prod_img: "https://www.creedfragrance.com/cdn/shop/files/Viking.jpg" },
    // --- 29. PRADA ---
    { brand: "Prada", name: "L'Homme Prada", price: "365.00", prod_img: "https://www.prada.com/dw/image/v2/BFYF_PRD/on/demandware.static/-/Sites-prada-master-catalog/default/dw4c5c2c25/LHomme_Prada.jpg" },
    { brand: "Prada", name: "Luna Rossa Carbon", price: "340.00", prod_img: "https://www.prada.com/dw/image/v2/BFYF_PRD/on/demandware.static/-/Sites-prada-master-catalog/default/dw12b4e8c9/LR_Carbon.jpg" },
    { brand: "Prada", name: "Paradoxe EDP", price: "440.00", prod_img: "https://www.prada.com/dw/image/v2/BFYF_PRD/on/demandware.static/-/Sites-prada-master-catalog/default/dw7f3b8a3e/Paradoxe.jpg" },
    { brand: "Prada", name: "Amber Pour Homme", price: "320.00", prod_img: "https://www.prada.com/dw/image/v2/BFYF_PRD/on/demandware.static/-/Sites-prada-master-catalog/default/dw1a2b3c/Amber_PH.jpg" },
    { brand: "Prada", name: "Infusion d'Iris", price: "380.00", prod_img: "https://www.prada.com/dw/image/v2/BFYF_PRD/on/demandware.static/-/Sites-prada-master-catalog/default/dw2b3c4d/Infusion_Iris.jpg" },
    { brand: "Prada", name: "Luna Rossa Black", price: "360.00", prod_img: "https://www.prada.com/dw/image/v2/BFYF_PRD/on/demandware.static/-/Sites-prada-master-catalog/default/dw3c4d5e/LR_Black.jpg" },
    { brand: "Prada", name: "Candy EDP", price: "390.00", prod_img: "https://www.prada.com/dw/image/v2/BFYF_PRD/on/demandware.static/-/Sites-prada-master-catalog/default/dw4d5e6f/Candy.jpg" },
    { brand: "Prada", name: "L'Homme Intense", price: "395.00", prod_img: "https://www.prada.com/dw/image/v2/BFYF_PRD/on/demandware.static/-/Sites-prada-master-catalog/default/dw5e6f7g/LHomme_Intense.jpg" },
    { brand: "Prada", name: "Luna Rossa Ocean EDP", price: "370.00", prod_img: "https://www.prada.com/dw/image/v2/BFYF_PRD/on/demandware.static/-/Sites-prada-master-catalog/default/dw6f7g8h/LR_Ocean.jpg" },
    { brand: "Prada", name: "La Femme Prada", price: "410.00", prod_img: "https://www.prada.com/dw/image/v2/BFYF_PRD/on/demandware.static/-/Sites-prada-master-catalog/default/dw7g8h9i/La_Femme.jpg" },

    // --- 30. GUCCI ---
    { brand: "Gucci", name: "Gucci Bloom", price: "395.00", prod_img: "https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1493393403/488830_99999_0000_002_Light-Gucci-Bloom.jpg" },
    { brand: "Gucci", name: "Guilty Pour Homme EDP", price: "380.00", prod_img: "https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1582212904/568852_99999_0000_002_Light-Gucci-Guilty.jpg" },
    { brand: "Gucci", name: "Flora Gorgeous Gardenia", price: "420.00", prod_img: "https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1626342904/665114_99999_0000_002_Light-Flora.jpg" },
    { brand: "Gucci", name: "Gucci Rush", price: "310.00", prod_img: "https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1444342904/Gucci_Rush.jpg" },
    { brand: "Gucci", name: "The Alchemist's Garden (Oud)", price: "1100.00", prod_img: "https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1545342904/Oud_Gucci.jpg" },
    { brand: "Gucci", name: "Guilty Elixir Homme", price: "460.00", prod_img: "https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1682342904/Guilty_Elixir.jpg" },
    { brand: "Gucci", name: "Memoire d'une Odeur", price: "290.00", prod_img: "https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1562342904/Memoire.jpg" },
    { brand: "Gucci", name: "Gucci Bamboo", price: "340.00", prod_img: "https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1441342904/Bamboo.jpg" },
    { brand: "Gucci", name: "Envy Me", price: "320.00", prod_img: "https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1442342904/Envy_Me.jpg" },
    { brand: "Gucci", name: "Guilty Absolute", price: "390.00", prod_img: "https://media.gucci.com/style/DarkGray_Center_0_0_490x490/1482342904/Guilty_Absolute.jpg" },

    // --- 31. MONTALE ---
    { brand: "Montale", name: "Arabians Tonka", price: "420.00", prod_img: "https://montaleparfums.com/images/products/arabians_tonka.jpg" },
    { brand: "Montale", name: "Intense Cafe", price: "385.00", prod_img: "https://montaleparfums.com/images/products/intense_cafe.jpg" },
    { brand: "Montale", name: "Honey Aoud", price: "385.00", prod_img: "https://montaleparfums.com/images/products/honey_aoud.jpg" },
    { brand: "Montale", name: "Black Aoud", price: "385.00", prod_img: "https://montaleparfums.com/images/products/black_aoud.jpg" },
    { brand: "Montale", name: "Roses Musk", price: "385.00", prod_img: "https://montaleparfums.com/images/products/roses_musk.jpg" },
    { brand: "Montale", name: "Red Vetyver", price: "385.00", prod_img: "https://montaleparfums.com/images/products/red_vetyver.jpg" },
    { brand: "Montale", name: "Starry Nights", price: "385.00", prod_img: "https://montaleparfums.com/images/products/starry_nights.jpg" },
    { brand: "Montale", name: "Sensual Instinct", price: "410.00", prod_img: "https://montaleparfums.com/images/products/sensual_instinct.jpg" },
    { brand: "Montale", name: "Dark Purple", price: "385.00", prod_img: "https://montaleparfums.com/images/products/dark_purple.jpg" },
    { brand: "Montale", name: "Ristretto Intense Cafe", price: "440.00", prod_img: "https://montaleparfums.com/images/products/ristretto.jpg" },

    // --- 32. AZZARO ---
    { brand: "Azzaro", name: "The Most Wanted Parfum", price: "360.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw6c6c19f5/TMW_Parfum.jpg" },
    { brand: "Azzaro", name: "Wanted by Night", price: "320.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dwdf9d2c25/Wanted_Night.jpg" },
    { brand: "Azzaro", name: "Chrome", price: "240.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw1a2b3c/Chrome.jpg" },
    { brand: "Azzaro", name: "Azzaro Pour Homme", price: "210.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw2b3c4d/Azzaro_PH.jpg" },
    { brand: "Azzaro", name: "Wanted Girl", price: "340.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw3c4d5e/Wanted_Girl.jpg" },
    { brand: "Azzaro", name: "Visit For Men", price: "180.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw4d5e6f/Visit.jpg" },
    { brand: "Azzaro", name: "Chrome Extreme", price: "290.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw5e6f7g/Chrome_Extreme.jpg" },
    { brand: "Azzaro", name: "Solarissimo", price: "220.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw6f7g8h/Solarissimo.jpg" },
    { brand: "Azzaro", name: "The Most Wanted Intense", price: "350.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw7g8h9i/TMW_Intense.jpg" },
    { brand: "Azzaro", name: "Mademoiselle Azzaro", price: "260.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw8h9i0j/Mademoiselle.jpg" },

    // --- 33. MANCERA (Suite) ---
    { brand: "Mancera", name: "French Riviera", price: "420.00", prod_img: "https://manceraparfums.com/img/p/french_riviera.jpg" },
    { brand: "Mancera", name: "Aoud Vanille", price: "380.00", prod_img: "https://manceraparfums.com/img/p/aoud_vanille.jpg" },
    { brand: "Mancera", name: "Fig Extasy", price: "395.00", prod_img: "https://manceraparfums.com/img/p/fig_extasy.jpg" },
    { brand: "Mancera", name: "Amber Fever", price: "380.00", prod_img: "https://manceraparfums.com/img/p/amber_fever.jpg" },
    { brand: "Mancera", name: "Melody of the Sun", price: "410.00", prod_img: "https://manceraparfums.com/img/p/melody_sun.jpg" },
    { brand: "Mancera", name: "Soleil d'Italie", price: "380.00", prod_img: "https://manceraparfums.com/img/p/soleil_italie.jpg" },
    { brand: "Mancera", name: "Blue Aoud", price: "380.00", prod_img: "https://manceraparfums.com/img/p/blue_aoud.jpg" },
    { brand: "Mancera", name: "Wild Python", price: "390.00", prod_img: "https://manceraparfums.com/img/p/wild_python.jpg" },
    { brand: "Mancera", name: "Sicily", price: "380.00", prod_img: "https://manceraparfums.com/img/p/sicily.jpg" },
    { brand: "Mancera", name: "Kumkat Wood", price: "380.00", prod_img: "https://manceraparfums.com/img/p/kumkat_wood.jpg" },
       // --- 31. MONTALE ---
    { brand: "Montale", name: "Arabians Tonka", price: "420.00", prod_img: "https://montaleparfums.com/img/p/arabians_tonka.jpg" },
    { brand: "Montale", name: "Intense Cafe", price: "385.00", prod_img: "https://montaleparfums.com/img/p/intense_cafe.jpg" },
    { brand: "Montale", name: "Honey Aoud", price: "385.00", prod_img: "https://montaleparfums.com/img/p/honey_aoud.jpg" },
    { brand: "Montale", name: "Black Aoud", price: "385.00", prod_img: "https://montaleparfums.com/img/p/black_aoud.jpg" },
    { brand: "Montale", name: "Roses Musk", price: "385.00", prod_img: "https://montaleparfums.com/img/p/roses_musk.jpg" },
    { brand: "Montale", name: "Red Vetyver", price: "385.00", prod_img: "https://montaleparfums.com/img/p/red_vetyver.jpg" },
    { brand: "Montale", name: "Starry Nights", price: "385.00", prod_img: "https://montaleparfums.com/img/p/starry_nights.jpg" },
    { brand: "Montale", name: "Sensual Instinct", price: "410.00", prod_img: "https://montaleparfums.com/img/p/sensual_instinct.jpg" },
    { brand: "Montale", name: "Dark Purple", price: "385.00", prod_img: "https://montaleparfums.com/img/p/dark_purple.jpg" },
    { brand: "Montale", name: "Ristretto Intense Cafe", price: "440.00", prod_img: "https://montaleparfums.com/img/p/ristretto.jpg" },

    // --- 32. AZZARO ---
    { brand: "Azzaro", name: "The Most Wanted Parfum", price: "360.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw6c6c19f5/TMW_Parfum.jpg" },
    { brand: "Azzaro", name: "Wanted by Night", price: "320.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dwdf9d2c25/Wanted_Night.jpg" },
    { brand: "Azzaro", name: "Chrome", price: "240.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw1a2b3c/Chrome.jpg" },
    { brand: "Azzaro", name: "Azzaro Pour Homme", price: "210.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw2b3c4d/Azzaro_PH.jpg" },
    { brand: "Azzaro", name: "Wanted Girl", price: "340.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw3c4d5e/Wanted_Girl.jpg" },
    { brand: "Azzaro", name: "Chrome Extreme", price: "290.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw5e6f7g/Chrome_Extreme.jpg" },
    { brand: "Azzaro", name: "The Most Wanted Intense", price: "350.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw7g8h9i/TMW_Intense.jpg" },
    { brand: "Azzaro", name: "Azzaro Sport", price: "150.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw8h9i0j/Sport.jpg" },
    { brand: "Azzaro", name: "Chrome Pure", price: "250.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw9i0j1k/Pure.jpg" },
    { brand: "Azzaro", name: "Wanted Eau de Parfum", price: "330.00", prod_img: "https://www.azzaro.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-azzaro-master-catalog/default/dw0j1k2l/Wanted_EDP.jpg" },

    // --- 33. GIORGIO ARMANI ---
    { brand: "Armani", name: "Acqua di Gio Profondo", price: "385.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw4c5c2c25/ADG_Profondo.jpg" },
    { brand: "Armani", name: "Stronger With You Intensely", price: "350.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw12b4e8c9/SWY_Intensely.jpg" },
    { brand: "Armani", name: "Acqua di Gio Parfum", price: "410.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw7f3b8a3e/ADG_Parfum.jpg" },
    { brand: "Armani", name: "My Way Le Parfum", price: "430.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw1a2b3c/My_Way.jpg" },
    { brand: "Armani", name: "Code Parfum", price: "395.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw2b3c4d/Code_Parfum.jpg" },
    { brand: "Armani", name: "Si Passione", price: "410.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw3c4d5e/Si_Passione.jpg" },
    { brand: "Armani", name: "Stronger With You Absolutely", price: "370.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw4d5e6f/SWY_Absolutely.jpg" },
    { brand: "Armani", name: "Armani Privé Bois d'Encens", price: "950.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw5e6f7g/Bois_Encens.jpg" },
    { brand: "Armani", name: "Acqua di Gio Eau de Parfum", price: "360.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw6f7g8h/ADG_EDP.jpg" },
    { brand: "Armani", name: "Code Eau de Toilette", price: "310.00", prod_img: "https://www.armanibeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-armani-master-catalog/default/dw7g8h9i/Code_EDT.jpg" },

    // --- 34. YVES SAINT LAURENT ---
    { brand: "YSL", name: "Myslf EDP", price: "390.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw6c6c19f5/Myslf.jpg" },
    { brand: "YSL", name: "Libre Le Parfum", price: "450.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dwdf9d2c25/Libre_LP.jpg" },
    { brand: "YSL", name: "Y Eau de Parfum", price: "370.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw1a2b3c/Y_EDP.jpg" },
    { brand: "YSL", name: "La Nuit de L'Homme", price: "340.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw2b3c4d/LNDH.jpg" },
    { brand: "YSL", name: "Black Opium Over Red", price: "420.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw3c4d5e/BO_Red.jpg" },
    { brand: "YSL", name: "Y Elixir", price: "460.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw4d5e6f/Y_Elixir.jpg" },
    { brand: "YSL", name: "Tuxedo (Vestiaire)", price: "850.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw5e6f7g/Tuxedo.jpg" },
    { brand: "YSL", name: "Kouros", price: "280.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw6f7g8h/Kouros.jpg" },
    { brand: "YSL", name: "L'Homme", price: "320.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw7g8h9i/LHomme.jpg" },
    { brand: "YSL", name: "Babycat", price: "920.00", prod_img: "https://www.yslbeauty.fr/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-ysl-master-catalog/default/dw8h9i0j/Babycat.jpg" },

    // --- 35. HERMÈS ---
    { brand: "Hermès", name: "Terre d'Hermès Pure Parfum", price: "410.00", prod_img: "https://www.hermes.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-hermes-master-catalog/default/dw6c6c19f5/Terre.jpg" },
    { brand: "Hermès", name: "H24 Herbes Vives", price: "360.00", prod_img: "https://www.hermes.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-hermes-master-catalog/default/dwdf9d2c25/H24.jpg" },
    { brand: "Hermès", name: "Un Jardin sur le Nil", price: "320.00", prod_img: "https://www.hermes.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-hermes-master-catalog/default/dw1a2b3c/Nil.jpg" },
    { brand: "Hermès", name: "Twilly d'Hermès", price: "340.00", prod_img: "https://www.hermes.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-hermes-master-catalog/default/dw2b3c4d/Twilly.jpg" },
    { brand: "Hermès", name: "Voyage d'Hermès", price: "380.00", prod_img: "https://www.hermes.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-hermes-master-catalog/default/dw3c4d5e/Voyage.jpg" },
    { brand: "Hermès", name: "Eau d'Orange Verte", price: "290.00", prod_img: "https://www.hermes.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-hermes-master-catalog/default/dw4d5e6f/Orange_Verte.jpg" },
    { brand: "Hermès", name: "Ambre Narguilé", price: "880.00", prod_img: "https://www.hermes.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-hermes-master-catalog/default/dw5e6f7g/Ambre.jpg" },
    { brand: "Hermès", name: "Terre d'Hermès Givrée", price: "370.00", prod_img: "https://www.hermes.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-hermes-master-catalog/default/dw6f7g8h/Givree.jpg" },
    { brand: "Hermès", name: "Jour d'Hermès", price: "350.00", prod_img: "https://www.hermes.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-hermes-master-catalog/default/dw7g8h9i/Jour.jpg" },
    { brand: "Hermès", name: "Bel Ami Vetiver", price: "390.00", prod_img: "https://www.hermes.com/dw/image/v2/AAKI_PRD/on/demandware.static/-/Sites-hermes-master-catalog/default/dw8h9i0j/BelAmi.jpg" },

    // --- 36. FREDERIC MALLE ---
    { brand: "Frederic Malle", name: "Portrait of a Lady", price: "1150.00", prod_img: "https://www.fredericmalle.fr/media/products/Portrait.jpg" },
    { brand: "Frederic Malle", name: "Musc Ravageur", price: "850.00", prod_img: "https://www.fredericmalle.fr/media/products/Musc.jpg" },
    { brand: "Frederic Malle", name: "The Night", price: "2400.00", prod_img: "https://www.fredericmalle.fr/media/products/TheNight.jpg" },
    { brand: "Frederic Malle", name: "French Lover", price: "780.00", prod_img: "https://www.fredericmalle.fr/media/products/FrenchLover.jpg" },
    { brand: "Frederic Malle", name: "Eau de Magnolia", price: "690.00", prod_img: "https://www.fredericmalle.fr/media/products/Magnolia.jpg" },
    { brand: "Frederic Malle", name: "Bigarade Concentree", price: "720.00", prod_img: "https://www.fredericmalle.fr/media/products/Bigarade.jpg" },
    { brand: "Frederic Malle", name: "Une Rose", price: "880.00", prod_img: "https://www.fredericmalle.fr/media/products/UneRose.jpg" },
    { brand: "Frederic Malle", name: "Vetiver Extraordinaire", price: "820.00", prod_img: "https://www.fredericmalle.fr/media/products/Vetiver.jpg" },
    { brand: "Frederic Malle", name: "Carnal Flower", price: "950.00", prod_img: "https://www.fredericmalle.fr/media/products/Carnal.jpg" },
    { brand: "Frederic Malle", name: "Promise", price: "1050.00", prod_img: "https://www.fredericmalle.fr/media/products/Promise.jpg" },

    // --- 37. PENHALIGON'S ---
    { brand: "Penhaligon's", name: "The Tragedy of Lord George", price: "890.00", prod_img: "https://www.penhaligons.com/LordGeorge.jpg" },
    { brand: "Penhaligon's", name: "Halfeti", price: "780.00", prod_img: "https://www.penhaligons.com/Halfeti.jpg" },
    { brand: "Penhaligon's", name: "Changing Constance", price: "850.00", prod_img: "https://www.penhaligons.com/Constance.jpg" },
    { brand: "Penhaligon's", name: "Juniper Sling", price: "620.00", prod_img: "https://www.penhaligons.com/Juniper.jpg" },
    { brand: "Penhaligon's", name: "Endymion Concentré", price: "650.00", prod_img: "https://www.penhaligons.com/Endymion.jpg" },
    { brand: "Penhaligon's", name: "Blenheim Bouquet", price: "580.00", prod_img: "https://www.penhaligons.com/Blenheim.jpg" },
    { brand: "Penhaligon's", name: "The Coveted Duchess Rose", price: "890.00", prod_img: "https://www.penhaligons.com/DuchessRose.jpg" },
    { brand: "Penhaligon's", name: "Quercus", price: "550.00", prod_img: "https://www.penhaligons.com/Quercus.jpg" },
    { brand: "Penhaligon's", name: "Sartorial", price: "610.00", prod_img: "https://www.penhaligons.com/Sartorial.jpg" },
    { brand: "Penhaligon's", name: "Cairo", price: "750.00", prod_img: "https://www.penhaligons.com/Cairo.jpg" },

    // --- 38. BYREDO ---
    { brand: "Byredo", name: "Bal d'Afrique", price: "720.00", prod_img: "https://www.byredo.com/BalDAfrique.jpg" },
    { brand: "Byredo", name: "Gypsy Water", price: "720.00", prod_img: "https://www.byredo.com/GypsyWater.jpg" },
    { brand: "Byredo", name: "Mojave Ghost", price: "720.00", prod_img: "https://www.byredo.com/MojaveGhost.jpg" },
    { brand: "Byredo", name: "Rose of No Man's Land", price: "720.00", prod_img: "https://www.byredo.com/Rose.jpg" },
    { brand: "Byredo", name: "Blanche", price: "720.00", prod_img: "https://www.byredo.com/Blanche.jpg" },
    { brand: "Byredo", name: "Super Cedar", price: "720.00", prod_img: "https://www.byredo.com/Cedar.jpg" },
    { brand: "Byredo", name: "Black Saffron", price: "720.00", prod_img: "https://www.byredo.com/Saffron.jpg" },
    { brand: "Byredo", name: "Bibliothèque", price: "750.00", prod_img: "https://www.byredo.com/Bibliotheque.jpg" },
    { brand: "Byredo", name: "Slow Dance", price: "720.00", prod_img: "https://www.byredo.com/SlowDance.jpg" },
    { brand: "Byredo", name: "Mixed Emotions", price: "720.00", prod_img: "https://www.byredo.com/Emotions.jpg" },

    // --- 39. ACQUA DI PARMA ---
    { brand: "Acqua Di Parma", name: "Colonia Futura", price: "390.00", prod_img: "https://www.acquadiparma.com/Colonia.jpg" },
    { brand: "Acqua Di Parma", name: "Fico di Amalfi", price: "320.00", prod_img: "https://www.acquadiparma.com/Fico.jpg" },
    { brand: "Acqua Di Parma", name: "Mirto di Panarea", price: "320.00", prod_img: "https://www.acquadiparma.com/Mirto.jpg" },
    { brand: "Acqua Di Parma", name: "Oud & Spice", price: "680.00", prod_img: "https://www.acquadiparma.com/Oud.jpg" },
    { brand: "Acqua Di Parma", name: "Bergamotto di Calabria", price: "320.00", prod_img: "https://www.acquadiparma.com/Bergamotto.jpg" },
    { brand: "Acqua Di Parma", name: "Arancia di Capri", price: "320.00", prod_img: "https://www.acquadiparma.com/Arancia.jpg" },
    { brand: "Acqua Di Parma", name: "Leather", price: "650.00", prod_img: "https://www.acquadiparma.com/Leather.jpg" },
    { brand: "Acqua Di Parma", name: "Zafferano", price: "710.00", prod_img: "https://www.acquadiparma.com/Zafferano.jpg" },
    { brand: "Acqua Di Parma", name: "Sandalo", price: "650.00", prod_img: "https://www.acquadiparma.com/Sandalo.jpg" },
    { brand: "Acqua Di Parma", name: "Yuzu", price: "650.00", prod_img: "https://www.acquadiparma.com/Yuzu.jpg" },

    // --- 40. ROJA PARFUMS ---
    { brand: "Roja", name: "Elysium Pour Homme Parfum", price: "1250.00", prod_img: "https://www.rojaparfums.com/Elysium.jpg" },
    { brand: "Roja", name: "Enigma Pour Homme", price: "1350.00", prod_img: "https://www.rojaparfums.com/Enigma.jpg" },
    { brand: "Roja", name: "Manhattan", price: "1100.00", prod_img: "https://www.rojaparfums.com/Manhattan.jpg" },
    { brand: "Roja", name: "Apex", price: "950.00", prod_img: "https://www.rojaparfums.com/Apex.jpg" },
    { brand: "Roja", name: "Oceania", price: "1200.00", prod_img: "https://www.rojaparfums.com/Oceania.jpg" },
    { brand: "Roja", name: "Amber Aoud", price: "1850.00", prod_img: "https://www.rojaparfums.com/AmberAoud.jpg" },
    { brand: "Roja", name: "Diaghilev", price: "2400.00", prod_img: "https://www.rojaparfums.com/Diaghilev.jpg" },
    { brand: "Roja", name: "Sweetie Aoud", price: "1650.00", prod_img: "https://www.rojaparfums.com/Sweetie.jpg" },
    { brand: "Roja", name: "Burlington 1819", price: "1150.00", prod_img: "https://www.rojaparfums.com/Burlington.jpg" },
    { brand: "Roja", name: "Danger Pour Homme", price: "1100.00", prod_img: "https://www.rojaparfums.com/Danger.jpg" },

    // --- 41. SERGE LUTENS ---
    { brand: "Serge Lutens", name: "Ambre Sultan", price: "480.00", prod_img: "https://www.sergelutens.com/Ambre.jpg" },
    { brand: "Serge Lutens", name: "Chergui", price: "480.00", prod_img: "https://www.sergelutens.com/Chergui.jpg" },
    { brand: "Serge Lutens", name: "La Fille de Berlin", price: "480.00", prod_img: "https://www.sergelutens.com/Berlin.jpg" },
    { brand: "Serge Lutens", name: "Muscs Koublai Khan", price: "720.00", prod_img: "https://www.sergelutens.com/Muscs.jpg" },
    { brand: "Serge Lutens", name: "Five O'Clock Au Gingembre", price: "480.00", prod_img: "https://www.sergelutens.com/Gingembre.jpg" },

    // --- 42. JO MALONE LONDON ---
    { brand: "Jo Malone", name: "Wood Sage & Sea Salt", price: "350.00", prod_img: "https://www.jomalone.com/Sage.jpg" },
    { brand: "Jo Malone", name: "English Pear & Freesia", price: "350.00", prod_img: "https://www.jomalone.com/Pear.jpg" },
    { brand: "Jo Malone", name: "Myrrh & Tonka", price: "450.00", prod_img: "https://www.jomalone.com/Myrrh.jpg" },
    { brand: "Jo Malone", name: "Pomegranate Noir", price: "350.00", prod_img: "https://www.jomalone.com/Pomegranate.jpg" },
    { brand: "Jo Malone", name: "Oud & Bergamot", price: "450.00", prod_img: "https://www.jomalone.com/Oud.jpg" },

    // --- 43. MEMO PARIS ---
    { brand: "Memo Paris", name: "African Leather", price: "680.00", prod_img: "https://www.memoparis.com/African.jpg" },
    { brand: "Memo Paris", name: "Irish Leather", price: "680.00", prod_img: "https://www.memoparis.com/Irish.jpg" },
    { brand: "Memo Paris", name: "Marfa", price: "680.00", prod_img: "https://www.memoparis.com/Marfa.jpg" },
    { brand: "Memo Paris", name: "French Leather", price: "680.00", prod_img: "https://www.memoparis.com/French.jpg" },
    { brand: "Memo Paris", name: "Inlé", price: "680.00", prod_img: "https://www.memoparis.com/Inle.jpg" },

    // --- 44. JULIETTE HAS A GUN ---
    { brand: "JHAG", name: "Not A Perfume", price: "320.00", prod_img: "https://www.juliettehasagun.com/NotAPerfume.jpg" },
    { brand: "JHAG", name: "Lust For Sun", price: "380.00", prod_img: "https://www.juliettehasagun.com/Lust.jpg" },
    { brand: "JHAG", name: "Vanilla Vibes", price: "340.00", prod_img: "https://www.juliettehasagun.com/Vanilla.jpg" },
    { brand: "JHAG", name: "Lady Vengeance", price: "360.00", prod_img: "https://www.juliettehasagun.com/Lady.jpg" },
    { brand: "JHAG", name: "Pear Inc.", price: "320.00", prod_img: "https://www.juliettehasagun.com/Pear.jpg" },

    // --- 45. MAISON MARGIELA (REPLICA) ---
    { brand: "Margiela", name: "By the Fireplace", price: "380.00", prod_img: "https://www.maisonmargiela.com/Fireplace.jpg" },
    { brand: "Margiela", name: "Jazz Club", price: "380.00", prod_img: "https://www.maisonmargiela.com/Jazz.jpg" },
    { brand: "Margiela", name: "Beach Walk", price: "380.00", prod_img: "https://www.maisonmargiela.com/Beach.jpg" },
    { brand: "Margiela", name: "Sailing Day", price: "380.00", prod_img: "https://www.maisonmargiela.com/Sailing.jpg" },
    { brand: "Margiela", name: "Lazy Sunday Morning", price: "380.00", prod_img: "https://www.maisonmargiela.com/Lazy.jpg" },

    // --- 46. INITIO PARFUMS PRIVÉS ---
    { brand: "Initio", name: "Side Effect", price: "820.00", prod_img: "https://www.initioparfums.com/Side.jpg" },
    { brand: "Initio", name: "Oud for Greatness", price: "890.00", prod_img: "https://www.initioparfums.com/Oud.jpg" },
    { brand: "Initio", name: "Rehab", price: "780.00", prod_img: "https://www.initioparfums.com/Rehab.jpg" },
    { brand: "Initio", name: "Atomic Rose", price: "780.00", prod_img: "https://www.initioparfums.com/Atomic.jpg" },
    { brand: "Initio", name: "Absolute Aphrodisiac", price: "750.00", prod_img: "https://www.initioparfums.com/Absolute.jpg" },

    // --- 47. Histoires de Parfums --
    { brand: "HdP", name: "1899 Hemingway", price: "420.00", prod_img: "https://www.histoiresdeparfums.com/1899.jpg" },
    { brand: "HdP", name: "1725 Casanova", price: "420.00", prod_img: "https://www.histoiresdeparfums.com/1725.jpg" },
    { brand: "HdP", name: "1740 Marquis de Sade", price: "450.00", prod_img: "https://www.histoiresdeparfums.com/1740.jpg" },
    { brand: "HdP", name: "Ambre 114", price: "420.00", prod_img: "https://www.histoiresdeparfums.com/114.jpg" },
    { brand: "HdP", name: "This is not a Blue Bottle", price: "380.00", prod_img: "https://www.histoiresdeparfums.com/Blue.jpg" },

    // --- 48. Tiziana Terenzi ---
    { brand: "Tiziana Terenzi", name: "Kirke", price: "520.00", prod_img: "https://www.tizianaterenzi.com/Kirke.jpg" },
    { brand: "Tiziana Terenzi", name: "Laudano Nero", price: "480.00", prod_img: "https://www.tizianaterenzi.com/Laudano.jpg" },
    { brand: "Tiziana Terenzi", name: "Orion", price: "550.00", prod_img: "https://www.tizianaterenzi.com/Orion.jpg" },
    { brand: "Tiziana Terenzi", name: "Cassiopea", price: "520.00", prod_img: "https://www.tizianaterenzi.com/Cassiopea.jpg" },
    { brand: "Tiziana Terenzi", name: "Draco", price: "520.00", prod_img: "https://www.tizianaterenzi.com/Draco.jpg" },

    // --- 49. Vilhelm Parfumerie ---
    { brand: "Vilhelm", name: "Morning Chess", price: "580.00", prod_img: "https://www.vilhelmparfumerie.com/Morning.jpg" },
    { brand: "Vilhelm", name: "Poets of Berlin", price: "580.00", prod_img: "https://www.vilhelmparfumerie.com/Poets.jpg" },
    { brand: "Vilhelm", name: "Dear Polly", price: "580.00", prod_img: "https://www.vilhelmparfumerie.com/Polly.jpg" },
    { brand: "Vilhelm", name: "Mango Aves", price: "580.00", prod_img: "https://www.vilhelmparfumerie.com/Mango.jpg" },
    { brand: "Vilhelm", name: "Basilico & Fellini", price: "580.00", prod_img: "https://www.vilhelmparfumerie.com/Basilico.jpg" },

    // --- 50. Nasomatto ---
    { brand: "Nasomatto", name: "Black Afgano", price: "450.00", prod_img: "https://www.nasomatto.com/Black.jpg" },
    { brand: "Nasomatto", name: "Baraonda", price: "450.00", prod_img: "https://www.nasomatto.com/Baraonda.jpg" },
    { brand: "Nasomatto", name: "Duro", price: "450.00", prod_img: "https://www.nasomatto.com/Duro.jpg" },
    { brand: "Nasomatto", name: "Pardon", price: "450.00", prod_img: "https://www.nasomatto.com/Pardon.jpg" },
    { brand: "Nasomatto", name: "Silver Musk", price: "450.00", prod_img: "https://www.nasomatto.com/Silver.jpg" },

    // --- 51. Etat Libre d'Orange ---
    { brand: "ELDO", name: "You Or Someone Like You", price: "380.00", prod_img: "https://www.etatlibredorange.com/You.jpg" },
    { brand: "ELDO", name: "Fat Electrician", price: "380.00", prod_img: "https://www.etatlibredorange.com/Fat.jpg" },
    { brand: "ELDO", name: "Remarkable People", price: "380.00", prod_img: "https://www.etatlibredorange.com/Remarkable.jpg" },
    { brand: "ELDO", name: "I Am Trash", price: "380.00", prod_img: "https://www.etatlibredorange.com/Trash.jpg" },
    { brand: "ELDO", name: "Exit The King", price: "380.00", prod_img: "https://www.etatlibredorange.com/Exit.jpg" },

    // --- 52. L'Artisan Parfumeur ---
    { brand: "L'Artisan", name: "Mure et Musc", price: "410.00", prod_img: "https://www.artisanparfumeur.fr/Mure.jpg" },
    { brand: "L'Artisan", name: "Premier Figuier", price: "410.00", prod_img: "https://www.artisanparfumeur.fr/Figuier.jpg" },
    { brand: "L'Artisan", name: "Timbuktu", price: "410.00", prod_img: "https://www.artisanparfumeur.fr/Timbuktu.jpg" },
    { brand: "L'Artisan", name: "Noir Exquis", price: "450.00", prod_img: "https://www.artisanparfumeur.fr/Noir.jpg" },
    { brand: "L'Artisan", name: "Tea for Two", price: "410.00", prod_img: "https://www.artisanparfumeur.fr/Tea.jpg" },

    // --- 53. Goldfield & Banks ---
    { brand: "G&B", name: "Ingenious Ginger", price: "490.00", prod_img: "https://www.goldfieldandbanks.com/Ginger.jpg" },
    { brand: "G&B", name: "Sunset Hour", price: "490.00", prod_img: "https://www.goldfieldandbanks.com/Sunset.jpg" },
    { brand: "G&B", name: "Pacific Rock Moss", price: "490.00", prod_img: "https://www.goldfieldandbanks.com/RockMoss.jpg" },
    { brand: "G&B", name: "Bohemian Lime", price: "490.00", prod_img: "https://www.goldfieldandbanks.com/Lime.jpg" },
    { brand: "G&B", name: "Desert Rosewood", price: "490.00", prod_img: "https://www.goldfieldandbanks.com/Rosewood.jpg" },

    // --- 54. Escentric Molecules ---
    { brand: "Escentric", name: "Molecule 01", price: "320.00", prod_img: "https://www.escentric.com/M01.jpg" },
    { brand: "Escentric", name: "Molecule 02", price: "320.00", prod_img: "https://www.escentric.com/M02.jpg" },
    { brand: "Escentric", name: "Escentric 01", price: "320.00", prod_img: "https://www.escentric.com/E01.jpg" },
    { brand: "Escentric", name: "Molecule 01 + Iris", price: "380.00", prod_img: "https://www.escentric.com/Iris.jpg" },
    { brand: "Escentric", name: "Molecule 01 + Patchouli", price: "380.00", prod_img: "https://www.escentric.com/Patchouli.jpg" },

    // --- 55. Commodity ---
    { brand: "Commodity", name: "Milk Expressive", price: "390.00", prod_img: "https://www.commodityfragrances.com/Milk.jpg" },
    { brand: "Commodity", name: "Gold Expressive", price: "390.00", prod_img: "https://www.commodityfragrances.com/Gold.jpg" },
    { brand: "Commodity", name: "Book Expressive", price: "390.00", prod_img: "https://www.commodityfragrances.com/Book.jpg" },
    { brand: "Commodity", name: "Paper Personal", price: "390.00", prod_img: "https://www.commodityfragrances.com/Paper.jpg" },
    { brand: "Commodity", name: "Moss Bold", price: "390.00", prod_img: "https://www.commodityfragrances.com/Moss.jpg" },

    // --- 56. Phlur ---
    { brand: "Phlur", name: "Missing Person", price: "320.00", prod_img: "https://www.phlur.com/Missing.jpg" },
    { brand: "Phlur", name: "Father Figure", price: "320.00", prod_img: "https://www.phlur.com/Father.jpg" },
    { brand: "Phlur", name: "Solar Power", price: "320.00", prod_img: "https://www.phlur.com/Solar.jpg" },
    { brand: "Phlur", name: "Tangerine Boy", price: "320.00", prod_img: "https://www.phlur.com/Tangerine.jpg" },
    { brand: "Phlur", name: "Lost Cause", price: "320.00", prod_img: "https://www.phlur.com/Lost.jpg" },

    // --- 57. MATIERE PREMIERE ---
    { brand: "Matiere", name: "Radical Rose", price: "620.00", prod_img: "https://www.matiere-premiere.com/Radical.jpg" },
    { brand: "Matiere", name: "Parisian Musc", price: "620.00", prod_img: "https://www.matiere-premiere.com/Parisian.jpg" },
    { brand: "Matiere", name: "Encens Suave", price: "620.00", prod_img: "https://www.matiere-premiere.com/Encens.jpg" },
    { brand: "Matiere", name: "Cologne Cedrat", price: "550.00", prod_img: "https://www.matiere-premiere.com/Cedrat.jpg" },
    { brand: "Matiere", name: "Falcon Leather", price: "620.00", prod_img: "https://www.matiere-premiere.com/Falcon.jpg" },

    // --- 58. Nishane ---
    { brand: "Nishane", name: "Hacivat", price: "780.00", prod_img: "https://www.nishane.com/Hacivat.jpg" },
    { brand: "Nishane", name: "Ani", price: "720.00", prod_img: "https://www.nishane.com/Ani.jpg" },
    { brand: "Nishane", name: "Hundred Silent Ways", price: "650.00", prod_img: "https://www.nishane.com/HSW.jpg" },
    { brand: "Nishane", name: "Fan Your Flames", price: "720.00", prod_img: "https://www.nishane.com/FYF.jpg" },
    { brand: "Nishane", name: "Wulong Cha", price: "650.00", prod_img: "https://www.nishane.com/Wulong.jpg" },

    // --- 59. Fragrance Du Bois ---
    { brand: "FDB", name: "Oud Jaune Intense", price: "1450.00", prod_img: "https://www.fragrancedubois.com/Jaune.jpg" },
    { brand: "FDB", name: "Oud Orange Intense", price: "1450.00", prod_img: "https://www.fragrancedubois.com/Orange.jpg" },
    { brand: "FDB", name: "Sahraa", price: "1850.00", prod_img: "https://www.fragrancedubois.com/Sahraa.jpg" },
    { brand: "FDB", name: "Minuit et Demi", price: "980.00", prod_img: "https://www.fragrancedubois.com/Minuit.jpg" },
    { brand: "FDB", name: "Siberian Rose", price: "850.00", prod_img: "https://www.fragrancedubois.com/Rose.jpg" },

    // --- 60. Clive Christian ---
    { brand: "Clive Christian", name: "No. 1 Masculine", price: "2400.00", prod_img: "https://www.clivechristian.com/No1.jpg" },
    { brand: "Clive Christian", name: "X Masculine", price: "1250.00", prod_img: "https://www.clivechristian.com/X.jpg" },
    { brand: "Clive Christian", name: "C Woody Leather", price: "1100.00", prod_img: "https://www.clivechristian.com/C.jpg" },
    { brand: "Clive Christian", name: "1872 Masculine", price: "1050.00", prod_img: "https://www.clivechristian.com/1872.jpg" },
    { brand: "Clive Christian", name: "Blonde Amber", price: "1450.00", prod_img: "https://www.clivechristian.com/Blonde.jpg" }
];
